name: agent-ci

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint --test

  test:
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm i

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: ./vendor/bin/pest --compact

  auto-merge:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    environment: Testing
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check PR labels for auto-merge eligibility
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(l => l.name);

            // Auto-merge if labeled 'agent-developed' and risk is low
            const isAgentDeveloped = labels.includes('agent-developed');
            const isLowRisk = !labels.includes('high-risk') && !labels.includes('needs-review');

            core.setOutput('should_merge', isAgentDeveloped && isLowRisk);
            core.setOutput('reason', isAgentDeveloped && isLowRisk
              ? 'Agent-developed PR, low risk, CI passed'
              : 'Requires human review');

      - name: Auto-merge PR
        if: steps.check.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash',
              commit_title: context.payload.pull_request.title,
            });
