name: deploy-production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          npm ci

      - name: Build Assets
        run: npm run build

      - name: Snapshot Current State
        env:
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          PRODUCTION_PATH: ${{ secrets.PRODUCTION_PATH }}
          DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
        run: |
          chmod +x scripts/snapshot.sh
          scripts/snapshot.sh production

      - name: Deploy to Production
        env:
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          PRODUCTION_PATH: ${{ secrets.PRODUCTION_PATH }}
          DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
        run: |
          chmod +x scripts/deploy.sh
          scripts/deploy.sh production

      - name: Run Health Checks
        env:
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
        run: |
          chmod +x scripts/health-check.sh
          scripts/health-check.sh "$PRODUCTION_URL"

      - name: Observation Period
        env:
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
        run: |
          echo "Starting 15-minute observation period..."
          for i in $(seq 1 3); do
            sleep 300
            echo "Observation check $i/3 at $(date -u +%H:%M:%S)..."
            scripts/health-check.sh "$PRODUCTION_URL"
          done
          echo "Observation period complete. All checks passed."

      - name: Rollback on Failure
        if: failure()
        env:
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          PRODUCTION_PATH: ${{ secrets.PRODUCTION_PATH }}
          DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
        run: |
          echo "DEPLOYMENT FAILED — initiating rollback"
          chmod +x scripts/rollback.sh
          scripts/rollback.sh production

      - name: Create Rollback Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[CRITICAL] Production deployment failed — rolled back ${context.sha.substring(0, 7)}`,
              body: [
                '## Production Deployment Failure',
                '',
                `**Commit:** ${context.sha}`,
                `**Rolled back at:** ${new Date().toISOString()}`,
                `**Workflow:** ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
                '',
                'The deployment was automatically rolled back to the previous known-good state.',
                'Please investigate the failure before attempting to re-deploy.',
              ].join('\n'),
              labels: ['deployment-failure', 'production', 'critical'],
            });
