name: deploy-staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          npm ci

      - name: Build Assets
        run: npm run build

      - name: Deploy to Staging
        env:
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
          STAGING_PATH: ${{ secrets.STAGING_PATH }}
          DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        run: |
          chmod +x scripts/deploy.sh
          scripts/deploy.sh staging

      - name: Run Health Checks
        env:
          STAGING_URL: ${{ secrets.STAGING_URL }}
        run: |
          chmod +x scripts/health-check.sh
          scripts/health-check.sh "$STAGING_URL"

      - name: Rollback on Failure
        if: failure()
        env:
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
          STAGING_PATH: ${{ secrets.STAGING_PATH }}
          DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        run: |
          chmod +x scripts/rollback.sh
          scripts/rollback.sh staging

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Deploy] Staging deployment failed for ${context.sha.substring(0, 7)}`,
              body: `Staging deployment failed and was rolled back.\n\nCommit: ${context.sha}\nWorkflow: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['deployment-failure', 'staging'],
            });
